#!/bin/sh
 
untilsuccessful () {
	"$@"
	while [ $? -ne 0 ]; do
		echo Retrying...
		sleep 1
		"$@"
	done
}

IP=`hostname --ip-address`
SEED=$1

# Start Couchbase in background
su - couchbase -c "/opt/couchbase/bin/couchbase-server -- -noinput"
PID=$!

# Init Couchbase
if [ -n "$SEED" ]; then
	echo "Make Couchbase ($IP) join the cluster via $SEED"
	untilsuccessful couchbase-cli server-add -c $SEED \
		--user=$CB_USERNAME --password=$CB_PASSWORD \
		--server-add=$IP
else
	echo "Make Couchbase ($IP) the first cluster node"
	untilsuccessful couchbase-cli cluster-init -c $IP \
		--cluster-init-username=$CB_USERNAME \
		--cluster-init-password=$CB_PASSWORD
	untilsuccessful couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=hemlock --bucket-password=password --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=128 --bucket-replica=0 -u Administrator -p password
        
        untilsuccessful curl -v -u Administrator:password 127.0.0.1:8091/pools/default/remoteClusters \
		-d uuid=9eee38236f3bf28406920213d93981a5  \
		-d name=hemlock \
		-d hostname=127.0.0.1:9091 \
		-d username=Administrator -d password=password

	curl -v -u Administrator:password http://127.0.0.1:8091/pools > /tmp/pools.txt
	UUID=$(cat /tmp/pools.txt | jq '.uuid')

	sleep 100
	curl -v -X POST -u Administrator:password http://127.0.0.1:8091/controller/createReplication \
		-d uuid=$UUID \
		-d fromBucket=hemlock \
		-d toCluster=hemlock \
		-d toBucket=hemlock \
		-d replicationType=continuous
fi
