#!/usr/bin/env bash

set -x

HIPACHE_CONTAINER=$(docker ps | grep hipache | cut -d" " -f1)

if [[ -z "$HIPACHE_CONTAINER" ]]; then
    echo "hipache is not running"
    exit 1
fi


HOST=172.17.42.1
export DOCKER_HOST=$HOST
export HIPACHE_PORT=80
DENDRITE_DOMAIN=dendrite

export REDIS_PORT=$(docker port $HIPACHE_CONTAINER 6379)
export REDIS_HOST=$HOST

DENDRITE_CONTAINER=$(docker run -d \
    -e REDIS_HOST=$REDIS_HOST \
    -e REDIS_PORT=$REDIS_PORT \
    -e DOCKER_HOST=$DOCKER_HOST \
    -e HIPACHE_PORT=80 \
    172.17.42.1:80/try-challenges)

DENDRITE_PORT=$(docker port $DENDRITE_CONTAINER 5000)
DENDRITE_HOST=$HOST

# clear out old keys
redis-cli -h $REDIS_HOST -p $REDIS_PORT del frontend:$DENDRITE_DOMAIN
redis-cli -h $REDIS_HOST -p $REDIS_PORT rpush frontend:$DENDRITE_DOMAIN api
redis-cli -h $REDIS_HOST -p $REDIS_PORT rpush frontend:$DENDRITE_DOMAIN http://$DENDRITE_HOST:$DENDRITE_PORT
